### ISSUE TITLE
Shouldn't the input be an array or support a builder interface

### ISSUE THREAD

**Issue by vjpr** [tudvari/dockerfile-generator#4]
You can use COPY in two different lines for example. Current design seems to not support this.

Or use a builder interface like https://github.com/matutter/dockerfilejs

**Comment by tudvari** [comment]
You are able to use multiple COPY and ADD command in the input, but these lines are successive in the output. This behaviour coms from the input, which should be a valid JSON document.

You can see example in the libTests.js file in the repository. If you have any suggestion, please share with me.

**Comment by tudvari** [comment]
@vjpr Hi! Sorry for the delay, thanks to your suggestion, the latest release (3.2.0) has a new API for generate dockerfile from a array, which means you are able to use multiple items.
